from setuptools import setup, find_packages

setup(
    name="lerna",
    version="3.0.0",
    packages=find_packages(),
    author="Shaheryar Sadaqat",
    author_email="research@lerna.ai",
    description="LERNA: Learning Efficiency Ratio Navigation & Adaptation - Energy-efficient LLM fine-tuning",
    long_description=open("README.md", encoding="utf-8").read() if __import__("os").path.exists("README.md") else "",
    long_description_content_type="text/markdown",
    url="https://gitlab.com/f43434f-group1/lerna",
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.30.0",
        "datasets>=2.10.0",
        "evaluate>=0.4.0",
        "accelerate>=0.20.0",
        "scipy>=1.7.0",
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "psutil>=5.9.0",
        "pyyaml>=6.0",
        "tqdm>=4.62.0",
    ],
    extras_require={
        "wandb": ["wandb>=0.15.0"],
        "viz": ["matplotlib>=3.5.0", "seaborn>=0.11.0", "plotly>=5.13.0"],
        "dev": ["pytest>=7.0", "black", "ruff"],
        "all": [
            "wandb>=0.15.0",
            "matplotlib>=3.5.0",
            "seaborn>=0.11.0",
            "plotly>=5.13.0",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
